//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatálogoDeProductos.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CatálogoDeProductos.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a German.
        /// </summary>
        public static string btnAle {
            get {
                return ResourceManager.GetString("btnAle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categories.
        /// </summary>
        public static string btnCategorias {
            get {
                return ResourceManager.GetString("btnCategorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Light.
        /// </summary>
        public static string btnClaro {
            get {
                return ResourceManager.GetString("btnClaro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        public static string btnConfiguracion {
            get {
                return ResourceManager.GetString("btnConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string btnEng {
            get {
                return ResourceManager.GetString("btnEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string btnEsp {
            get {
                return ResourceManager.GetString("btnEsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a French.
        /// </summary>
        public static string btnFra {
            get {
                return ResourceManager.GetString("btnFra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Graphics.
        /// </summary>
        public static string btnGraficos {
            get {
                return ResourceManager.GetString("btnGraficos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        public static string btnInicio {
            get {
                return ResourceManager.GetString("btnInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dark.
        /// </summary>
        public static string btnOscuro {
            get {
                return ResourceManager.GetString("btnOscuro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Products.
        /// </summary>
        public static string btnProductos {
            get {
                return ResourceManager.GetString("btnProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit.
        /// </summary>
        public static string btnSalir {
            get {
                return ResourceManager.GetString("btnSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product Catalog.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Category.
        /// </summary>
        public static string txtAddCategoria {
            get {
                return ResourceManager.GetString("txtAddCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Product.
        /// </summary>
        public static string txtAddProducto {
            get {
                return ResourceManager.GetString("txtAddProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You need to restart the application to apply the language changes. Do you want to restart now?.
        /// </summary>
        public static string txtAviso {
            get {
                return ResourceManager.GetString("txtAviso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change language.
        /// </summary>
        public static string txtCambioDeIdioma {
            get {
                return ResourceManager.GetString("txtCambioDeIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of products per category.
        /// </summary>
        public static string txtCantidadDeProductosPorCategoria {
            get {
                return ResourceManager.GetString("txtCantidadDeProductosPorCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Category.
        /// </summary>
        public static string txtCategoria {
            get {
                return ResourceManager.GetString("txtCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categories View.
        /// </summary>
        public static string txtCategoriasView {
            get {
                return ResourceManager.GetString("txtCategoriasView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings View.
        /// </summary>
        public static string txtConfiguracionView {
            get {
                return ResourceManager.GetString("txtConfiguracionView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contact.
        /// </summary>
        public static string txtContacto {
            get {
                return ResourceManager.GetString("txtContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Category.
        /// </summary>
        public static string txtDeleteCategoria {
            get {
                return ResourceManager.GetString("txtDeleteCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Product.
        /// </summary>
        public static string txtDeleteProducto {
            get {
                return ResourceManager.GetString("txtDeleteProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        public static string txtDescripcion {
            get {
                return ResourceManager.GetString("txtDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deselect Category.
        /// </summary>
        public static string txtDeseleccionarCategoria {
            get {
                return ResourceManager.GetString("txtDeseleccionarCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deselect Product.
        /// </summary>
        public static string txtDeseleccionarProducto {
            get {
                return ResourceManager.GetString("txtDeseleccionarProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Category.
        /// </summary>
        public static string txtEditCategoria {
            get {
                return ResourceManager.GetString("txtEditCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Product.
        /// </summary>
        public static string txtEditProducto {
            get {
                return ResourceManager.GetString("txtEditProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string txtId {
            get {
                return ResourceManager.GetString("txtId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home View.
        /// </summary>
        public static string txtInicioView {
            get {
                return ResourceManager.GetString("txtInicioView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Languaje.
        /// </summary>
        public static string txtLenguaje {
            get {
                return ResourceManager.GetString("txtLenguaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string txtNombre {
            get {
                return ResourceManager.GetString("txtNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Price.
        /// </summary>
        public static string txtPrecio {
            get {
                return ResourceManager.GetString("txtPrecio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Products by price range.
        /// </summary>
        public static string txtProductosPorRangoDePrecios {
            get {
                return ResourceManager.GetString("txtProductosPorRangoDePrecios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Products View.
        /// </summary>
        public static string txtProductosView {
            get {
                return ResourceManager.GetString("txtProductosView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Theme.
        /// </summary>
        public static string txtTema {
            get {
                return ResourceManager.GetString("txtTema", resourceCulture);
            }
        }
    }
}
